export const numbers = [
    { number: "1", title: "", text: '1. Herzlich willkommen zum diesjährigen Adventskalender und unserer gemeinsamen Reise durch die Kaffeewelt. Ich begrüße alle neuen Gesichter (oder Gaumen und Nasen 😉) und hoffe, dass ihr nach dieser Erfahrung zu jenen werdet, die nun schon zum zweiten oder dritten Mal dabei sind. <br><br> Als Kaffeeröster von Dylan & Harper bin ich maßgeblich dafür verantwortlich, was euch in den kommenden Wochen in der Tasse begegnen wird. <br><br>    Der diesjährige Adventskalender ist komplett auf Kaffee fokussiert. Ich habe mir kaum Verschnaufpausen erlaubt und euch 22 Kaffees eingepackt. <br><br>    Acht Türchen werden nicht offiziell veröffentlicht, da die Erntemenge unter 30kg liegt und ich diese nur mit euch teilen möchte. Sollte euch eine dieser Raritäten gefallen, könnt ihr uns gerne per Mail oder auf den sozialen Medien schreiben und ihr könnt euch Nachschub holen, solange der Vorrat reicht. <br><br>    Nicht jeder Kaffee wird allen schmecken, das ist das Schöne an unseren Parzellenkaffees, jeder hat seinen eigenen Charakter und findet Anklang bei der einen oder anderen Brühmethode und Brüher/in. <br><br>    Euch erwartet eine geschmackliche Reise, die sensorische Erfahrungen bringen darf und auch Fehler beim Brühen erlaubt. Macht euch nicht allzu viele Gedanken den perfekten Shot hinzukriegen und stresst euch nicht. Nach zehn Jahren als Kaffeeröster erwarte ich auch nicht bei einem 30kg Sack die „perfekte“ Röstung zu finden, aber mit viel Erfahrung kann man dem sehr nah kommen. <br><br>    Also genießt unseren Auftakt mit dem diesjährigen Cuvee zur Winterzeit: <br><br>    Der „winterlich“ wird euch in verschiedenen Bundles bei uns im Shop erwarten. Da wir dieses Jahr zwei Adventskalender Editionen haben, gibt es den „winterlich“ auch in zwei Versionen. Sowohl die Filter als auch Espresso Röstung ist wohl balanciert, nussig, ganz leichte Fruchtnoten mit einer Karamellsüße. Die Komposition besteht aus einem yellow Catuai als pulped natural und red Catuai natural der Fazendas Dutra (beide werden bald auch sortenrein veröffentlicht), unser Java von der Finca Hamburgo ist dabei und abgerundet wird es mit einem alten Bekannten, dem Embauba. <br><br>    Wie die meisten von euch wissen, mache ich keine Cuvees, weil diese in der Kaffeewelt meist dazu genutzt werden, den Müll, den man in der Ecke des Lagers hat, loszuwerden. Tatsächlich zieht sich das bis in die Kleinröster-Szene hin. Wenn ihr euch eine dieser unzähligen „Mischungen“ anschaut, werdet ihr kaum Informationen zu dem Inhalt finden. In meinem Fall fällt es mir einfach schwer unsere herausragenden Parzellenkaffees dafür zu verwenden, aber wenn ich mir das vornehme, dann möchte ich auch eine Message dahinter haben. Der „winterlich“ soll gemütlich sein, ein Kaffee ohne darüber nachzudenken. Einfach mal abschalten, kein Flavorprofile, keine Analyse, einfach ein Genuss für die wichtigen Minuten des Tages. Die Basis bilden die beiden Brasilianer und werden ergänzt durch etwas spritzigen Mexikaner. Das karamellige und den Körper liefert der Embauba.', uri: "" }, 
    { number: "2", title: "title", text: "text", uri: "" }, 
    { number: "3", title: "title", text: "text", uri: "" }, 
    { number: "4", title: "title", text: "text", uri: "" }, 
    { number: "5", title: "title", text: "text", uri: "" }, 
    { number: "6", title: "title", text: "text", uri: "" }, 
    { number: "7", title: "title", text: "text", uri: "" }, 
    { number: "8", title: "title", text: "text", uri: "" }, 
    { number: "9", title: "title", text: "text", uri: "" }, 
    { number: "10", title: "title", text: "text", uri: "" }, 
    { number: "11", title: "title", text: "text", uri: "" }, 
    { number: "12", title: "title", text: "text", uri: "" }, 
    { number: "13", title: "title", text: "text", uri: "" }, 
    { number: "14", title: "title", text: "text", uri: "" }, 
    { number: "15", title: "title", text: "text", uri: "" }, 
    { number: "16", title: "title", text: "text", uri: "" }, 
    { number: "17", title: "title", text: "text", uri: "" }, 
    { number: "18", title: "title", text: "text", uri: "" }, 
    { number: "19", title: "title", text: "text", uri: "" }, 
    { number: "20", title: "title", text: "text", uri: "" }, 
    { number: "21", title: "title", text: "text", uri: "" }, 
    { number: "22", title: "title", text: "text", uri: "" }, 
    { number: "23", title: "title", text: "text", uri: "" },
    { number: "24", title: "title", text: "text", uri: "" }, 
]
