export const numbers = [
    { number: "17", title: "title", text: "", uri: "" }, 
    { number: "1", title: "Adventskalender 2022", text: "Gemahlene Kalender machen wir frisch in der letzten Novemberwoche, bitte schreiben Sie diesen Wunsch in die Bestellung mit hinein.", uri: "" }, 
    { number: "2", title: "title", text: "text", uri: "" }, 
    { number: "3", title: "title", text: "text", uri: "" }, 
    { number: "4", title: "title", text: "text", uri: "" }, 
    { number: "5", title: "title", text: "text", uri: "" }, 
    { number: "6", title: "title", text: "text", uri: "" }, 
    { number: "20", title: "title", text: "text", uri: "" }, 
    { number: "7", title: "title", text: "text", uri: "" }, 
    { number: "8", title: "title", text: "text", uri: "" }, 
    { number: "9", title: "title", text: "text", uri: "" }, 
    { number: "10", title: "title", text: "text", uri: "" }, 
    { number: "11", title: "title", text: "text", uri: "" }, 
    { number: "12", title: "title", text: "text", uri: "" }, 
    { number: "13", title: "title", text: "text", uri: "" }, 
    { number: "14", title: "title", text: "text", uri: "" }, 
    { number: "15", title: "title", text: "text", uri: "" }, 
    { number: "22", title: "title", text: "text", uri: "" }, 
    { number: "16", title: "title", text: "text", uri: "" }, 
    { number: "18", title: "title", text: "text", uri: "" }, 
    { number: "19", title: "title", text: "text", uri: "" }, 
    { number: "21", title: "title", text: "text", uri: "" }, 
    { number: "23", title: "title", text: "text", uri: "" },
    { number: "24", title: "title", text: "text", uri: "" }, 
]
